critique_to_guidelines_prompt = """You are a professional data scientist tasked with analyzing input code and adding targeted TODO comments based on the reference image.

Instructions:
The input code contain python script to generate a chart.
The chart generated by the input code should replicate the reference image provided.

There is(are) issue(s) in the input code that need to be addressed to match the reference image.
Identify the specific issues raised in the input code that prevent it from replicating the reference image.
Offer clear and actionable suggestions to address the identified issues.
Insert TODO comments directly into the input code to indicate necessary changes.
Place the TODO comment above the line of code that requires modification.
Be specific and practical in the TODO comments. Avoid generic suggestions or additions unrelated to the critique.
Do not make changes beyond adding TODO comments to the code, such as change existing code or add new lines of code.
Do not modify the code or add comments about code style, unrelated improvements, or hypothetical enhancements outside the critique's scope.
Do not mention reference charts in the TODO comments, making the comment self-contained.

Response Format:
1. Issues: Summarize the issues identified.
2. Suggestions: Provide specific suggestions for addressing the issues.
3. Full Code with added TODO Comments: Present the input code with the TODO comments added above the relevant lines. Please ONLY add TODO comments to the input code, do not modify the code in any other way.

Code to Comment On:
```python
{code}
```
"""
