code_revision_prompt = """
You are a professional data scientist tasked with revising the input code based on the visual critique provided.

### Objective:
The input code contains a Python script that generates a chart. 
The chart is intended to replicate the reference image, but there could be discrepancies between the two.
The chart that generated by input code has been reviewed by a data visualization expert who provided a visual critique. 
Your task is to revise the code to address the issues identified in the critique and improve the chart accordingly.
Identify the discrepancies and issues in the generated chart based on the critique.
Make necessary modifications to the input code to resolve the identified issues and improve the chart.
Match the existing style and structure of the input code. 
Ensure correctness and functionality.
Return the FULL revised code to ensure it is ready for the next stage of development.

### Inputs:
- Visual Critique:
{visual_critique}

- Code to Revise:
```python
{code}
```
"""